[package]
name = "reytan_download_http"
version = "0.1.0"
edition = "2021"
description = "reytan http download handler"
license = "Apache-2.0"
authors = ["Lauren Liberda <lauren@selfisekai.rocks>"]

[dependencies]
reytan_download_types = { path = "../download_types" }
