pipeline:
  test:
    image: distroless.dev/alpine-base:latest
    commands:
      - |
        echo "https://alpine.sakamoto.pl/alpine/edge/main
        https://alpine.sakamoto.pl/alpine/edge/community" > /etc/apk/repositories
      - apk add cargo curl-dev openssl-dev build-base
      - cargo fetch
      - cargo test --all
