[package]
name = "reytan"
version = "0.1.0"
edition = "2021"
description = "Extractor of metadata from various streaming services, in a unified format"
authors = [
    "Lauren Liberda <laura@selfisekai.rocks>",
]
keywords = ["scraper", "youtube"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
async-trait = "0.1.52"
futures = "^0.3"
lazy_static = "1.4.0"
nipper = "0.1.9"
reqwest = { version = "0.11.9", features = ["gzip", "brotli", "deflate", "cookies", "json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde-aux = "3.0.1"
serde_json = "1.0.79"
smart-default = "0.6.0"
tokio = { version = "1.16.1", features = ["full"] }
url = "2.2.2"
