[package]
name = "reytan_monorepo"
version = "0.1.0"
edition = "2021"
description = "Extractor of metadata from various streaming services, in a unified format"
authors = ["Lauren Liberda <lauren@selfisekai.rocks>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "src/context",
    "src/extractor_api",
    "src/extractors/bandcamp",
    "src/extractors/youtube",
]
